:PROPERTIES:
:ID:       B6D6922F-AF9F-4D6A-BE1D-7117897CF532
:END:
#+title: File

* Emacs Files
In Emacs, files are data stored on disk.

There are some commands for operating files.


#+CAPTION: Working with files
| *Binding* | *Meaning*                                               |
|---------+-------------------------------------------------------|
| *C-x C-f* | Open or create a file.                                |
| *C-x C-v* | Read an alternate file, replacing the one read with . |
| *C-x i*   | Insert file at cursor position.                       |
| *C-x C-s* | Save buffer.                                          |
| *C-x C-w* | Save buffer as another file.                          |


** Backup Files
The first time you save a file during an editing session, Emacs creates a backup file.
The name of the backup file is the same as the name of the file you’re editing, with a tilde ~ added.
For example, if you are editing the file text, the backup file is text~

** Auto-save Files
Emacs will auto save you files from time to time into auto-save files.
The name of an auto-save file is the same as the name of the file you are editing, with a sharp (#) added to the beginning and the end.
For example, if you are editing the file text, its auto-save file is #text#.

* Linux Files

A file is a sequence of bytes, nothing more and nothing less.
Every I/O device, including disks, keyboards, displays, and even networks, is modeled as a file.
This simple and elegant notion of a file is nonetheless very powerful because it provides applications with a uniform view of all the varied I/O devices that might be contained in the system.


* Text File and Binary File
Files that consists exclusively of ASCII characters are known as text files.
All other files are knowns as binary files.

