:PROPERTIES:
:ID:       3A889F30-C7A9-43CB-8F23-AAE11CA0B976
:END:
#+title: Window Type

A *window* describes the portion of the screen that Emacs uses to
display buffers. Every live window has one associated buffer, whose
contents appear in that window. By contrast, a given buffer may appear
in one window, no window, or several windows. Windows are grouped on the
screen into *frames*; each window belongs to one and only one frame.

Though many windows may exist simultaneously, at any time one window is
designated the selected window. This is the window where the cursor is
(usually) displayed when Emacs is ready for a command. The selected
window usually displays the current buffer, but this is not necessarily
the case.

Windows have no read syntax. They print in hash notation, giving the
window number and the name of the buffer being displayed. The window
numbers exist to identify windows uniquely, since the buffer displayed
in any given window can change frequently.

#+begin_example
(selected-window)                       ; #<window 3 on *scratch*>
#+end_example


